### ISSUE TITLE
[SUGGESTION] Don't place events/notes when holding alt.

### ISSUE THREAD

**Issue by K1ngC001** [DPS2004/Beatblock-issues#173] opened 2024-11-02 20:47 UTC
**Is your suggestion related to a problem? Please describe.**
It's just annoying when I'm holding alt to scroll through a song with the wheel thing, and I forget I have a block picked so it places one invertedly. It's out of the way to switch to "none" then use it. Not that big of a deal, but would be a quality of life fix or smth like that.

**Describe the solution you'd like**
Notes/events can't be placed when alt is held.

**Describe alternatives you've considered**
Maybe just don't place a note when using the wheel to navigate a level.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment] 2024-11-03 20:00
Duplicate of #155

**Closed by DPS2004** 2024-11-03 20:00 UTC
Labels: suggestion
