### ISSUE TITLE
[SUGGESTION] Linear tempo changes

### ISSUE THREAD

**Issue by TeraByte-Official** [DPS2004/Beatblock-issues#171] opened 2024-10-30 23:11 UTC
**Is your suggestion related to a problem? Please describe.**
Songs with linear tempo changes are very hard to chart without LITERALLY DOING CALCULUS

**Describe the solution you'd like**
Give the Tempo Chane event a duration modifier. This will allow the tempo change to be linear.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment] 2024-11-03 20:01
Duplicate of #29

**Closed by DPS2004** 2024-11-03 20:01 UTC
Labels: suggestion
