### ISSUE TITLE
Force Infobox On-screen

### ISSUE THREAD

**Issue by Smugly33810** [DPS2004/Beatblock-issues#130] opened 2024-09-02 02:29 UTC
**Is your suggestion related to a problem? Please describe.**
Not neccesarily its just that when the event editor is in its default position the infoboxes are usually offscreen.

**Describe the solution you'd like**
make the infoboxes bound to the other side of the (?) symbol 

**Describe alternatives you've considered**
Another easier option is to change the default position of the event editor to the other side of the screen and move the pallete chooser but im not sure people in the community would be fond of that

**Additional context**

![artists rendition](https://github.com/user-attachments/assets/226ef6bb-d1cf-4502-8ee3-58282e328862)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment] 2024-10-07 19:49
Duplicate of #16

**Closed by DPS2004** 2024-10-07 19:49 UTC
Labels: suggestion
